#cloud-config

# Update package manager on instance startup
package_update: true

# Install packages on the instance
packages:
  - nginx

# Run commands after instance startup (enable and start nginx)
runcmd:
  - systemctl enable --now nginx
